## Documentation: http://docs.travis-ci.com/user/languages/julia/
language: julia

os:
  - linux

julia:
  - 1.0
  - nightly

notifications:
  email: false

git:
  depth: 1

sudo: required
services:
  - docker


# Run test script in Launcher
# script:
#     - (cd deps; ./init.sh)
#     - julia --color=yes --project=Launcher -e "using Pkg; Pkg.build()"
#     - julia --color=yes --check-bounds=yes --project=Launcher -e "using Pkg; Pkg.test()"
script:
    echo "Skipping"

## deploy documentation
jobs:
  include:
    - stage: Documentation
      julia: 1.0
      os: linux
      script:
        - (cd deps; ./init.sh)
        - julia --project=docs -e 'using Pkg; Pkg.instantiate(); Pkg.develop(PackageSpec(path=joinpath(pwd(), "Launcher")))'
        - julia --project=docs --color=yes docs/make.jl
      after_success: skip
