## Documentation: http://docs.travis-ci.com/user/languages/julia/
language: julia
os:
  - linux
julia:
  - 1.0
notifications:
  email: false
git:
  depth: 1


# For now, just skip tests - will add this later
script:
    - echo "skipping tests"


## uncomment following lines to deploy documentation
jobs:
  include:
    - stage: Documentation
      julia: 1.0
      os: linux
      script:
        - julia --project=docs -e 'using Pkg; Pkg.instantiate(); Pkg.develop(PackageSpec(path=joinpath(pwd(), "Launcher")))'
        - julia --project=docs --color=yes docs/make.jl
      after_success: skip
